/**
 * Licensed Materials - Property of tenxcloud.com
 * (C) Copyright 2018 TenxCloud. All Rights Reserved.
 */

/**
 * App (template) create intl message
 *
 * @author zhangxuan
 * @date 2018-08-24
 */
import { defineIntlMessages } from '../../common/tools'

const messageObj = {
  prefix: 'AppCreate',
  data: {
    requestFailure: '请求错误',
    imageStoreError: '镜像仓库暂时无法访问，请联系管理员',
    imageName: '镜像名称',
    deploy: '部署',
    add: '添加',
    selectImage: '选择镜像',
    public: '公有',
    private: '私有',
    imageStore: '镜像商店',
    imagePlaceholder: '请输入镜像名称搜索',
    total: '共 {total} 条',
    wrapName: '包名称',
    publishName: '发布名称',
    tag: '版本标签',
    originalFile: '文件名称',
    wrapType: '包类型',
    uploadTime: '上传时间',
    operation: '操作',
    selectWrap: '选择应用包',
    wrap: '应用包',
    wrapStore: '应用包商店',
    wrapStorePlaceholder: '请输入包名称或发布名称搜索',
    wrapPlaceholder: '请输入包名称搜索',
    uploadWrap: '去上传部署包',
    totalPrice: '合计',
    priceHour: '{RMB}{priceHour}/{unit}小时',
    priceMonth: '合 {RMB}{priceMonth}{unit}/月',
    calculateResource: '计算资源',
    formsError: '表单信息有误',
    appTemplateCreating: '应用模板创建中',
    appTemplateCreateFailure: '应用模板创建失败',
    appTemplateCreateSuccess: '应用模板创建成功',
    cancel: '取消',
    previous: '上一步',
    overview: '信息总览',
    appTemplateName: '模板名称',
    appTemplateVersion: '模板版本',
    appTemplateDesc: '模板描述',
    service: '服务',
    keepAddService: '继续添加服务',
    serviceTooltip: '至少添加一个服务',
    save: '保存',
    create: '创建',
    deleteFailure: '删除失败',
    deleteTooltip: '至少保留一个服务',
    appTemplate: '应用模板',
    deleteService: '删除服务',
    deleteServiceTip: '删除服务无法恢复，是否确认删除？',
    returnToPrevious: '返回上一步',
    returnToPreviousTip: '返回上一步，将会放弃当前正在编辑的配置信息，本次编辑的信息将不会保留，是否返回上一步？',
    imageWarehouse: '镜像仓库',
    wrapManage: '应用包管理',
    addService: '添加服务',
    serviceConfig: '服务配置',
    deployMethod: '部署方式',
    selectTemplate: '选择模板',
    configService: '配置服务',
    selectApp: '选择应用',
    layoutFile: '编排文件',
    selectOperatingEnv: '选择运行环境',
    createAppByWarehouse: '通过镜像仓库创建应用',
    createServerByWarehouse: '通过镜像仓库创建服务',
    createAppByImageStore: '通过镜像商店创建应用',
    createServerByImageStore: '通过镜像商店创建服务',
    wrapDeploy: '应用包部署',
    createAppByWrap: '通过应用包文件创建应用',
    createServerByWrap: '通过应用包文件创建服务',
    createAppByWrapStore: '通过应用商店创建应用',
    createServerByWrapStore: '通过应用商店创建服务',
    createAppByAppTemplate: '通过应用模板创建应用',
    createServerByAppTemplate: '通过应用模板创建服务',
    aiModelApp: 'AI 模型应用',
    nextStep: '下一步',
    latestVersion: '最新版本',
    selectWrapTip: '请先选择应用包',
    serviceRepeatTip: '应用下已有设置entryPkgID的服务',
    imageAddressAcquisitionFailed: '镜像地址获取失败',
    refreshTip: '尝试刷新后重试',
    versionWrong: '版本有误，请重新选择版本',
    connectToOracle: '连接Oracle',
    open: '开',
    close: '关',
    selectBaseImage: '选择基础镜像',
    operatingEnv: '运行环境',
    operatingEnvTip: '设置 JAVA_OPTS：在下一步『配置服务』页面，配置环境变量中修改 JAVA_OPTS 键对应的值',
    selectVersion: '选择版本',
    advancedSettings: '高级设置',
    deployWrap: '部署应用',
    notSupportAppTemplate: '添加服务暂不支持应用模板',
    notSupportLayoutFile: '添加服务暂不支持编排文件方式',
    enterAddress: '请输入地址',
    enterCorrectAddress: '请输入正确的地址',
    thisItem: '此项',
    username: '用户名',
    pleaseEnter: '请输入{item}',
    maxLength: '输入不能超过64个字符',
    usernameReg: '请输入英文字母、数字、下划线',
    port: '端口',
    number: '数字',
    portRange: '端口范围1 ~ 65535',
    password: '密码',
    enterJndiName: '请输入JNDI名，最多可输入128位字符',
    databaseType: '数据库类型',
    address: '地址',
    dbAddressPlaceholder: '请输入数据库地址 (所在主机IP)',
    serviceName: '服务名称',
    jndiName: 'JNDI名',
    jndiPlaceholder: '请输入连接的实例名',
    appName: '应用名称',
    loadLayoutFileFailed: '加载编排文件失败，请检查后重试.',
    pleaseSelectLayoutFile: '请选择编排文件',
    createAppFailed: '创建应用失败',
    clusterResourceInsufficient: '集群资源不足',
    resourceExist: '相关资源已经存在，请修改后重试',
    checking: '校验中',
    appDesc: '应用描述',
    selectLayoutFile: '选择编排',
    layoutContent: '编排内容',
    layoutReturnTip: '返回上一步,改动将丢失',
    confirm: '确认',
    shutDown: '关闭',
    name: '名称',
    description: '描述',
    core: '核',
    memory: '内存',
    selectedConfiguration: '当前已选配置',
    remainingConfiguration: '剩余最大可选配置',
    officialImage: '官方镜像',
    all: '全部',
    webServer: 'Web服务器',
    databaseAndCache: '数据库与缓存',
    operatingSystem: '操作系统',
    middlewareAndOther: '中间件与其他',
    imageSquare: '镜像广场',
    lastModified: '修改时间',
    deleteSuccess: '删除成功',
    wrapDeleteTip: '只有未发布、已拒绝、已下架的应用包可被删除',
    publishing: '发布中',
    publishSuccess: '发布成功',
    publishFailure: '发布失败',
    select: '选择',
    traditionalDeploy: '传统部署',
    submitReview: '提交审核',
    uploadAttachment: '上传附件',
    updatePkg: '更新应用包',
    publish: '发布',
    download: '下载',
    delete: '删除',
    containerDeploy: '容器部署',
    classifyName: '分类名称',
    status: '状态',
    deleteTagTip: '确定要删除所选版本？',
    publishTip: '该应用包已通过管理员审核，点击确认即可发布到应用包商店，确认发布？',
    selectAppTemplate: '选择应用模板',
    appTemplatePlaceholder: '输入模板名称搜索',
    formsErrorTip: '请修改错误表单后，点击 [保存此服务并继续添加] 保存服务',
    createApp: '创建应用',
    failure: '失败',
    portConflict: '端口冲突，请检查服务端口',
    incorrect: '{item}不正确',
    env: '环境变量',
    loadSecurityGroupFailure: '获取安全组数据出错',
    editSecurityGroupFailure: '修改安全组隔离对象出错',
    finishAddServices: '完成添加服务',
    pleaseSelectOperatingEnv: '请选择运行环境',
    pleaseBindModelSet: '请绑定模型集',
    keepAdding: '继续添加',
    containerImage: '容器镜像',
    pleaseCorrectWrongForm: '请先修改错误的表单',
    pleaseFillInServiceName: '请先填写服务名称',
    pleaseCancelEdit: '请您先取消编辑',
    modify: '修改',
    noServiceTip: '本应用中暂无任何服务',
    appList: '应用列表',
    addedService: '已添加服务',
    confirmReturnToPreviousTip: '是否确定返回“上一步”？确定后已添加的服务 {services} 将不被保留',
    confirmSaveService: '是否确定保存该服务？',
    cluster: '集群',
    notExist: '不存在',
    loadBalance: '应用负载均衡',
    clusterNoPublicNexport: '集群未添加公网出口',
    clusterNoInternalNexport: '集群未添加内网出口',
    configurationGroup: '配置组',
    nameExisted: '名称重复',
    secretConfiguration: '加密配置',
    clusterDisableHostStorage: '集群禁用本地（host）存储',
    noApmInstalled: '没有安装amp',
    secretVariable: '加密变量',
    listener: '监听器',
    forwardingRules: '转发规则',
    existed: '重复',
    appTemplateResourceErrorTip: '以下模板引用资源不存在或不可用，您可以点击放弃，待解决资源故障后再行创建应用；或点击继续，手动修改服务配置，然后创建应用',
    resourceFailure: '资源故障',
    continue: '继续',
    abandon: '放弃',
    noTillerTip: '请先在集群中安装tiller插件并设置固定节点',
    addOneListener: '请至少添加一个监听器',
    mustAddServer: '请至少添加一个服务',
    mustAddOneNodeTag: "请至少添加一个服务与节点标签",
    mustAddOneServerTag: "请至少添加一个服务与服务标签",
  }
}

export default defineIntlMessages(messageObj)
