# Dockerfile.alpine
FROM mhart/alpine-node:6

# If you have native dependencies, you'll need extra tools
RUN apk add --no-cache bash git openssh

# Create app directory
RUN mkdir -p /usr/src/app
WORKDIR /usr/src/app

# ENV NODE_ENV production

# Install dependencies modules
RUN npm cache clean --force
COPY package.json /usr/src/app/
RUN npm set registry http://192.168.1.3:4873
RUN npm install && rm -f package.json
