# Dockerfile.alpine
FROM mhart/alpine-node:6

# Create app directory
RUN mkdir -p /usr/src/app
WORKDIR /usr/src/app

# Install dependencies modules
COPY package.json /usr/src/app/
# RUN npm install npm -g --registry=https://registry.npm.taobao.org
# RUN cnpm install && rm -f package.json

RUN npm cache clean --force
RUN npm install --registry=https://registry.npm.taobao.org && rm -f package.json