FROM 192.168.1.113/zhangpc/node:4.4.7

# Create app directory
RUN mkdir -p /usr/src/app
WORKDIR /usr/src/app

# Install dependencies modules
COPY package.json /usr/src/app/
RUN npm install npm -g --registry=https://registry.npm.taobao.org
# RUN npm install cnpm -g --registry=https://registry.npm.taobao.org
RUN npm install webpack -g --registry=https://registry.npm.taobao.org
# RUN cnpm install && rm -f package.json
RUN npm install --registry=https://registry.npm.taobao.org && rm -f package.json