/**
 * Licensed Materials - Property of tenxcloud.com
 * (C) Copyright 2018 TenxCloud. All Rights Reserved.
 */

/**
 *
 * intl for IndexPage
 * v0.1 - 2018-08-28
 *
 * @author zhangpc
 *
 */

import { defineIntlMessages } from '../../../common/tools'

export const mapData = {
  prefix: 'IndexPage',
  data: {
    overview: '总览',
    noAuth: '暂无总览查看权限，联系平台管理员授权',
    noData: '没有数据',
    running: '运行中',
    pending: '启动中',
    stopping: '停止中',
    stopped: '已停止',
    operating: '操作中',
    abnormal: '异   常  ',
    one: ' 个',
    memory: '内存',
    storage: '磁盘',
    apps: '应用 (个)',
    service: '服务 (个)',
    container: '容器 (个)',
    volume: '存储 (个)',
    snapshot: '快照 (个)',
    configuration: '服务配置 (个)',
    mysql: 'MySQL集群 (个)',
    redis: 'Redis集群 (个)',
    zookeeper: 'Zookeeper集群 (个)',
    elasticsearch: 'ES集群 (个)',
    project: '项目',
    personalProject: '个人项目',
    projectInfo: '项目信息',
    projectDetail: '项目详情',
    projectName: '项目名称：',
    shared: '共享',
    personal: '个人',
    projecRoles: '项目角色：',
    personalProjectNoRoles: '个人项目无角色',
    myBalance: '我的余额：',
    projectBalance: '项目余额：',
    todayConsumption: '今日消费：',
    allClusters: '全区域',
    go: '去查看',
    accountInfo: '账户信息',
    resourceQuotaOverview: '项目&集群相关资源配额',
    setQuota: '设置配额',
    seeDetails: '查看详情',
    computingResource: '计算资源',
    appManage: '应用管理',
    dbAndCache: '数据库&缓存',
    todayClusterInfo: '今日该集群记录',
    createApp: '创建应用',
    createService: '创建服务',
    createVolume: '创建存储卷',
    stopApp: '停止应用',
    delService: '删除服务',
    delVolume: '删除存储卷',
    updateApp: '修改应用',
    startApp: '启动应用',
    redeploy: '重新部署',
    sysStatus: '系统状态',
    app: '应用',
    serviceOnly: '服务',
    containerOnly: '容器',
    storageAndSnapshot: '存储与快照',
    sharedStorage: '共享型存储',
    rbdStorage: '独享型存储',
    hostStorage: '本地存储',
    rbdStorageSnapshot: '独享存储快照',
    computingResourceUsage: '计算资源使用率',
    computingResourceUsageTip: '显示使用率前三的节点',
    showMasterNode: '显示 Master 节点',
    nodeStatus: '主机状态',
    nodesSum: '主机总数',
    healthyNodesSum: '健康主机数',
    notEnabledNodesSum: '未启用主机数',
    continued: '持续',
    microsecond: '微秒',
    millisecond: '毫秒',
    second: '秒',
    minute: '分',
    hour: '时',
    audit: '审计日志',
    seeMore: '查看更多',
    unlimit: '无限制',
    pipelines: '流水线(个)',
    stages: '任务(个)',
    Dockerfile: 'Dockerfile(个)',
    cacheVolume: '缓存卷(个)',
    flow: '阶段(个)',
    stacks: '编排文件(个)',
    packages: '应用包(个)',
    projectResourceQuota: '项目资源配额',
    appCenter: '交付中心',
    todayProjectInfo: '今日该项目记录',
    buildSuccessfully: '构建成功',
    waitingForBuild: '待构建',
    inApproval: '审批处理中',
    refusedToExecute: '拒绝执行',
    approvalTimeout: '审批超时',
    abort: '人工停止',
    pipelineStatusStatistics: '流水线执行状态统计',
    buildFailed: '构建失败',
    building: '正在构建',
    serviceStatus: '服务状态：',
    healthy: '健康',
    harborProject: '镜像仓库',
    privateProject: '私有仓库组',
    privateImage: '私有镜像',
    publicHarbroProjects: '公开仓库组',
    publicImages: '公开镜像',
    alarm: '告警',
    noSysAlarm: '暂时无系统告警',
    svcNormal: '正常',
    svcWaring: '警告',
    svcNotInstall: '未安装',
    svcAbnormal: '异常',
    svcStopped: '已停止',
  },
}

export default defineIntlMessages(mapData)
