/**
 * Licensed Materials - Property of tenxcloud.com
 * (C) Copyright 2018 TenxCloud. All Rights Reserved.
*/

/**
 *
 * define Intl Msg for ClusterModule
 *
 * @author Songsz
 * @date 2018-08-23
 *
*/

import { defineIntlMessages } from "../../common/tools"
import React from "react";
import {Button} from "antd";
// data for index, clusterTabList
export const mapData = {
  prefix: 'hostList',
  data: {
    openDispatchSuccess: '开启调度成功',
    closeDispatchSuccess: '关闭调度成功',
    migrateUnfinishedNotExit: '容器迁移未完成，无法退出维护状态',
    health: '健康',
    notEnough: '不足',
    alarm: '告警',
    abnormal: '异常',
    inMaintenance: '维护中',
    migrateFail: '迁移失败',
    serverMigrating: '服务迁移中',
    running: '运行中',
    notDoWhenMigratingTip: '服务迁移过程最好不要进行其他操作，避免发生未知错误！',
    hasMigratedServer: '已迁移服务',
    nameOrIp: '名称/IP',
    status: '状态',
    role: '角色',
    monitorAlert: '监控告警',
    container: '容器',
    memory: '内存',
    dispatchStatus: '调度状态',
    diskCondition: '磁盘情况',
    joinClusterTime: '加入集群时间',
    operation: '操作',
    manageLabel: '管理标签',
    deleteNode: '删除节点',
    exitMaintain: '退出维护',
    nodeMaintain: '节点维护',
    checkMonitor: '查看监控',
    alertSetting: '告警设置',
    amount: '资源总量',
    assigned: '系统分配',
    use: '实际使用',
    useTips: '实际使用包含系统分配及节点上其它容器和进程使用的资源',
    maintainNoDispatchSwitch: '维护状态禁止使用调度开关',
    on: '开',
    off: '关',
    normalDispatch: '正常调度',
    pauseDispatch: '暂停调度',
    allowSysContainer: '允许分配系统容器',
    allowNewContainer: '允许分配新容器',
    notAllowNewContainer: '不允许分配新容器，正常运行的不受影响',
    notAllowSysContainer: '不允许分配系统容器，正常运行的不受影响',
    hostDetail: '主机详情',
    getNodeMonitorFail: '获取节点监控数据失败',
    setPrometheusHint: '安装 prometheus 插件后，即可获取集群监控数据',
    getNodeSourceFail: '获取节点资源数据失败',
    noTermNode: '没有可用终端节点，请联系管理员',
    canNotDelete: '不能删除',
    hostNodeDeleteSuccess: '主机节点删除成功',
    cancel: '取消',
    confirm: '确定',
    deleteErrForceMaintain: '删除问题资源，强制维护',
    nodeMaintainOpen: '节点维护开启中',
    userViolatedPdb: '用户 {namespace} 的服务 {resourceName} 违反了自己的pdb策略',
    containerMigrateFail: '容器迁移失败',
    nodeMaintainFail: '节点维护开启失败',
    nodeMaintainSuccess: '节点维护开启成功',
    exitNodeMaintain: '退出节点维护中',
    exitNodeMaintainFail: '退出节点维护失败',
    exitNodeMaintainSuccess: '退出节点维护成功',
    hostStorage: 'host 存储',
    bindLabel: '绑定标签',
    bindNode: '绑定节点',
    question: '问题',
    object: '对象',
    belongProject: '所属项目',
    belongServer: '所属服务',
    nodeErrorMigrateRisk: '该节点存在以下问题，部分容器有迁移风险',
    globalQuestion: '全局问题',
    nodeUseLoadBalance: '该节点被 {namespace} 项目 {resourceName} 负载均衡占用',
    nodeUseClusterNet: '该节点被设为集群网络出口',
    containerQuestion: '容器问题',
    licenseSupportNode: '当前许可证单个集群最多支持 {maxNodes} 个节点（目前已添加 {nodeSum} 个）',
    addHostNode: '添加主机节点',
    termOrClusterManage: '终端 | 集群管理',
    refresh: '刷 新',
    search: '搜索',
    totalNumber: '共 {number} 条',
    addHostNodeNote: '注意：新添加的主机需要与 Master 节点同一内网，可互通',
    deleteHostNode: '删除主机节点',
    confirmDeleteHostNode: '确定要删除 {nodeName} 主机节点？',
    deleteHostNodeNote: '注意：请保证其他开启调度状态的主机节点，剩余的配置足够运行所有应用的容器',
    nodeMaintainNote: '进入维护状态之后，节点调度状态将会关闭，节点上容器将会被随机迁移到其它可调度节点上；点击确定后进入维护状态，容器迁移完成后，才能退出维护状态',
    applicableScene: '适用场景',
    nodeCoreUpdate: '节点内核升级',
    hardSysMaintain: '硬件系统维护',
    replaceClusterNode: '替换集群节点',
    confirmAgain: '再次确认',
    maintainStatusCaution: '进入维护状态，会迁移容器，将会导致服务中断，请谨慎操作！',
    maintainStatusCautionAgain: '强制维护会强制迁移节点上所有容器资源，迁移过程会导致服务中断，请谨慎操作!',
    exitMaintainNote: '退出维护将恢复调度，允许调度新的容器到该节点上，请先确认是否完成维护工作，避免出现不必要的错误，影响您的使用体验，是否确定退出？',
    //TagDropDown.js
    labelValue: '标签值',
    noLabel: '暂无标签',
    labelKey: '标签键',
    selectHasNode: '选择已有节点',
    label: '标签',
    inputTextForShow: '请输入要显示的文字',
    adding: '添加中...',
    addSuccess: '添加成功！',
    addFail: '添加失败！',
    plsInputLabelKey: '请输入标签键',
    keyLength364: '标签键长度为3~63位',
    keyAlphaNumStart: '以字母或数字开头和结尾中间可(_-)',
    plsInputLabelValue: '请输入标签值',
    valueLength364: '标签值长度为3~63位',
    valueAlphaNumbStart: '以字母或数字开头和结尾中间可(_-)',
    labelHasRepeat: '标签已重复添加',
    labelHasExist: '标签已经存在',
    plsWriteLabelValue: '请填写标签值',
    plsWriteLabelKey: '请填写标签键',
    createLabel: '创建标签',
    //ManageLabelModal.js
    deleteLabelTip: '下列服务依赖此标签调度，从此主机删除此标签可能导致服务无法启动',
    user: '用户',
    app: '应用',
    server: '服务',
    confirmDeleteLabel: '确定要删除这个标签吗？',
    operationSuccess: '操作成功！',
    operationFail: '操作失败！',
    addAGroupLabel: '添加一组标签',
    addLabelFail: '添加标签失败！',
    or: '或',
    newLabel: '新建标签',
    lastHeartbeatTimeTips: '上次心跳时间与 Master 相差 {time}'
  }
}

export default defineIntlMessages(mapData)
