/**
 * Licensed Materials - Property of tenxcloud.com
 * (C) Copyright 2018 TenxCloud. All Rights Reserved.
*/

/**
 *
 * define Intl Msg for ClusterModule
 *
 * @author Songsz
 * @date 2018-08-23
 *
*/

import { defineIntlMessages } from "../../common/tools"
import React from "react";
// data for index, clusterTabList
export const mapData = {
  prefix: 'ClusterModule',
  data: {
    previewStep: '上一步',
    title: '集群管理',
    addClusterHelp: '基础设施，在这里您可以完成容器云平台的计算资源池管理：集群的添加、删除，以及集群内主机的添加、删除，并管理主机内的容器实例、查看主机维度的监控等。',
    addCluster: '添加集群',
    addClusterTip: '当前许可证最多支持 {maxClusters} 个集群（目前已添加 {clusterSum} 个）',
    noClusterPlsAdd: '暂无可用集群，请添加',
    configImgRepoAlert: '请先配置镜像仓库并添加集群，然后再进行其他操作',
    initConfig: '初始化配置',
    imgServerConfig: '镜像服务配置',
    submit: '提 交',
    back: '返 回',
    onlyOpenToEnterprise: '对企业内全部个人帐号开放该集群',
    inputDomain: '输入服务域名',
    serverDomain: '服务域名',
    description: '描述',
    inputServerOutIp: '请输入服务出口 IP',
    plsInputClusterName: '请填写集群名称',
    clusterNameErr: '集群名称不能超过18个字符',
    plsInputApiServer: '请填写 API Server',
    plsInputApiToken: '请填写 API Token',
    plsInputRightServerIp: '请填写正确的服务出口 IP',
    plsIptServerDomain: '请填写服务域名',
    plsIptRightServerDomain: '请填写正确的服务域名',
    plsSelect: '请选择',
    newCluster: '新建集群',
    newClusterAnnotation: '注：新建的首个集群，将设置对平台全部个人帐号开放',
    logout: '注销登录',
    finishAddCluster: '完成集群添加',
    addExistCluster: '添加已有集群',
    clusterName: '集群名称',
    apiHostPlaceholder: '协议 + API server 地址 + 端口号',
    serverOutIp: '服务出口 IP',
    addClusterNameSuccess: '添加集群 {clusterName} 成功',
    addClusterFail: '添加集群 {clusterName} 失败',
    apiHostValidatorErr: 'API Host 由协议 + API server 地址 + 端口号 组成',
    hasNoClusterAdd: '您还未添加集群，请添加',
    addClusterSuccess: '添加集群成功',
    checkClusterErr: '检测集群时发生错误，请重试',
    finishNNext: '完成并下一步',
    canAccessPublicNetwork: '可访问公网，暂不配置',
    imgServerAddress: '镜像服务地址',
    imgRepoUseFor: '该镜像仓库用途：',
    imgRepoUseFor1: '① 默认『系统组件』的容器镜像将从该仓库拉取，如可访问公网可略过',
    imgRepoUseFor2: '② 该仓库会作为平台 DevOps 的镜像仓库（交付中心、CI/CD 模块中使用）',
    savingImgServerConfig: '保存镜像服务配置中',
    imgServerAddressNotAvailable: '镜像服务地址不可用',
    imgServerSaveSuccess: '镜像服务配置保存成功',
    imgServerSaveFail: '镜像服务配置保存失败',
    plsInputRightImgServerAddress: '请填入合法的镜像服务地址',
    plsInputImgServerAddress: '请填写镜像服务地址',
    buildEnv: '构建环境',
    sourceOverview: '资源总览',
    hostList: '主机列表',
    labelManage: '标签管理',
    networkSolution: '网络方案',
    clusterStorage: '集群存储',
    clusterSet: '集群设置',
    addHostNode: '添加主机节点',
    createAlarmStrategy: '创建告警策略',
    createNewNotiGroup: '创建新通知组',
    addClusterOrNodeNote: '注意：新添加的主机需要与 Master 节点同一内网，可互通',
    noAvailableTermNode: '没有可用终端节点，请联系管理员',
    sysServiceManage: '系统服务管理',
    plsAddHosts: '请添加主机',
    clusterNameExist: '集群名称重复',
    clusterExist: '集群已存在',
    apiHostAndTokenExist: 'API host 和 API token 已经存在',
    backToCluster: '返回集群管理',
    addType: '添加方式',
    serviceProviderType: '接入服务商提供的主机',
    k8sType: '导入已有 Kubernetes 集群',
    selfBuiltType: '添加主机自建 Kubernetes 集群',
    cancel: '取消',
    confirm: '确定',
    authMethod: '认证方式',
    plsUploadFile: '请上传文件',
    createClusterSuccess: '创建集群成功',
    createClusterFailed: '创建集群失败',
    uploadFile: '上传文件',
    fileName: '文件名称',
    plsInputDesc: '请输入描述',
    addHostFailed: '添加主机失败',
    hostsExist: '节点 {ips} 已经存在',
    addNodes: '添加节点',
    clusterNodeSource: '集群节点来源',
    hostConfig: '主机配置',
    sltIaasSource: '选择 IaaS 来源',
    clusterConfig: '集群配置',
    diyIaas: '自定义添加主机',
    rcIaas: '云管--云星',
    k8sVersion: 'Kubernetes 版本',
    dockerVersion: 'Docker 版本',
    dockerTip: '默认安装v18.06.1-ce,若主机中已安装Docker，建议版本v18.06.1-ce',
    networkLayout: '网络规划',
    autoSelect: '自动选择',
    networkCidr: 'Pod 网络 CIDR',
    incorrectFormat: '格式不正确',
    networkPlanTip: '请填写有效的私有网，不能与 VPC 及 VPC 内已有 Kubernetes 集群使用的网段重复，创建成功后不能修改，Service 地址段也不能和 Pod 地址段重复',
    diyHostName: '自定义主机名称',
    diyHostNameTip: '非必填，若未自定义，显示实际主机名',
    hostIp: '主机 IP',
    hostConnectivity: '主机连接性',
    hostRole: '主机角色',
    operation: '操作',
    hostNameExist: '主机名称重复',
    hostIpAndPortExist: '主机 IP 和端口重复',
    plsSelectHostRole: '请选择主机角色',
    noneHosts: '暂未添加',
    hostName: '主机名',
    addHosts: '添加主机',
    twoMasterNotSupport: '不支持添加2个 Master 节点',
    masterExistsInCluster: '集群中已存在1个',
    oneMaster: '至少选择一个「可连接」的主机作为master节点',
    hostCheckError: '主机校验有误',
    hostIpAndPort: '主机 IP ：SSH 端口',
    hostUsername: '主机用户名',
    hostPassword: '主机密码',
    hostIpExist: '主机 IP 重复',
    hostIsRequired: '不能为空',
    hostPld: '如：192.168.1.1:22',
    usernamePld: '请输入用户名',
    passwordPld: '请输入密码',
    connectFailed: '连接失败',
    hostConnectFailed: '连接主机 {hosts} 连接失败',
    retryTip: '请修改IP/端口/用户名/密码后点击「确定」按钮重试',
    addExistHosts: '添加已有主机',
    checking: '正在校验',
    diffAddHosts: '不同用户名密码添加主机',
    sameAddHosts: '相同用户名密码批量添加主机',
    addOneHost: '添加一个主机',
    plsInputIp: '请输入 IP 地址',
    sameTipOne: '1、可以添加某个具体 IP 地址\\端口，如: 192.168.1.1:22',
    sameTipTwo: '2、也可以设置 IP 地址段, 如192.168.1.[1-10]:22',
    sameTipThree: '3、每行记录一条 IP 地址，换行分隔',
    sameUsername: '相同用户名',
    sameUsernamePld: '请输入相同用户名',
    samePassword: '相同密码',
    samePasswordPld: '请输入相同密码',
    hostnamePld: '请输入主机名称',
    cloudEnv: '云环境',
    rcHostnamePld: '默认显示云星上名字',
    nextStep: '下一步',
    hostNameWithIp: '主机名（主机 IP）',
    passwordRequired: '密码不能为空',
    rcModalTitle: '从云管平台--云星添加主机',
    add: '添加',
    remove: '移出',
    optionalHost: '可选主机',
    selectedHost: '已选主机',
    hostnamePrefix: '主机名称前缀',
    hostCount: '主机数量',
    network: '网络',
    image: '镜像',
    configuration: '配置',
    systemRandom: '系统随机',
    networkPld: '请选择网络',
    imagePld: '请选择镜像',
    configPld: '请选择配置',
    addHostByImage: '基于镜像添加主机',
    sltResourcePool: '选择资源池',
    resourcePoolPld: '请选择资源池',
    openStackTitle: '添加 OpenStack 主机池',
    availableDomain: '可用域',
    addResourcePool: '添加资源池',
    domainPld: '请选择可用域',
    securityGroup: '安全组',
    securityGroupPld: '请选择安全组',
    configSpecify: '配置规格',
    configSpecifyPld: '请选择配置规格',
    hostPoolConfig: '主机池配置',
    clusterCreatingTip: '添加中，完成后可查看集群详情',
    clusterCreateFailedTip: '创建失败',
    unconnected: '不可连接',
    connectable: '可连接',
    hostConnectivityTip: '至少有一个可连接的节点作为master节点',
    commandType: '执行命令添加'
  }
}

export default defineIntlMessages(mapData)
