import {defineIntlMessages} from '../../../common/tools'

export const mapData = {
  prefix: 'AppModule.AppServiceDetailIntl',
  data: {
    redeploy: '重新部署',
    loginTerminal: '登录终端',
    deleteOperation: '删除操作',
    deleteServiceinfo: '删除服务，该服务下的自动弹性伸缩策略也会被删除，确定要删除服务{ serviceName }吗?',
    serviceDetailPage: '服务详情页',
    status: '状态',
    address: '地址',
    containerObject: '容器实例',
    serviceAbout: '服务相关',
    basicsMessage: '基础信息',
    serviceMeshSwitch: '服务治理开关',
    assistSet: '辅助设置',
    configGroup: '配置组',
    fireWall: '安全组(防火墙)',
    unsupportbindDomain: '当前代理不支持绑定域名',
    visitStyle: '访问方式',
    port: '端口',
    currentProxynosupportHTTPS: '当前代理不支持设置 HTTPS',
    setHTTPS: '设置 HTTPS',
    livenessprobe: '高可用',
    monitor: '监控',
    strategy: '告警策略',
    autoScale: '自动伸缩',
    logs: '日志',
    events: '事件',
    rentalInfo: '租赁信息',
    serverTag: '服务标签',
    confirmPublished: '正在灰度发布，该服务暂不能做滚动发布操作',
    confirmPublishedAfter: ' 确认发布完成或确认发布回滚后方可进行下一次发布',
    AtleastVersion: '请至少为一个容器指定目标版本',
    fillin260stimes: '请填写 2~60s 间隔时间',
    fillin260sNumbers: '请填入 2~60 之间的数字',
    saving: '正在保存中...',
    servicePublishRoll: '服务 {serviceName} 滚动发布中...',
    servicePublishSuccess: '服务 {serviceName} 滚动发布已成功开启',
    servicePublishFailure: '服务 {serviceName} 开启滚动发布失败',
    rollPublish: '滚动发布',
    k8sContainerRollPublish: '提示: 检测到您的服务实例为k8s多容器 (Pod内多个容器) 实例,选择滚动发布时请确认下列服务实例中要升级的容器',
    noSupportRollPublish: 'Tips：挂载独享型存储的服务不支持滚动发布',
    rollPublishAlertRow: '滚动发布是指将应用完全更新为下面所选的目标版本，可升级也可回滚版本',
    serviceName: '服务名称',
    mirrorVersion: '镜像版本',
    appPackage: '应用包',
    targetVersion: '目标版本',
    pleaseChoiceVersion: '请选择目标版本',
    updateIntervalTime: '更新间隔时间',
    updateIntervalTimeInfo: '容器实例升级时间间隔，例如若为 0 秒，则 Pod 在 Ready 后就会被认为是可用状态，继续升级',
    suggest260s: '建议 2~60s',
    servicePrivateCache: '服务已挂载独享型存储，不能做灰度发布操作',
    serviceOneInstance:'服务只有 1 个实例，不能做灰度发布操作',
    greyPublish: '灰度发布',
    publishreroll: '发布回滚',
    openServiceSuccess: '服务 {serviceName} {msg}已成功开启',
    openServiceFailure: '服务 {serviceName} 开启{msg}失败',
    pleaseChoiceVersionNumber: '请选择目标版本数量',
    writeUpdateTimeInterval: '请填写更新间隔',
    confirmPublishreRool: '确认发布回滚',
    confirmPublishfinish: '确认发布完成',
    greyPublishInfo: '灰度发布，应用新老版本之间的平滑过渡，发布新版本时不直接替换旧版本，经过一段时间的版本共存来灰度验证。',
    greyPublishInfoStrong: '选择灰度发布后，在「灰度发布」期间不能进行「滚动发布」',
    allObjectNumber: '总实例数',
    greyPublishingInfo: '在灰度过程中，会有一个当前版本的过渡实例存在，灰度完成或回滚将删除该过渡实例',
    currentVersion: '当前版本',
    reRollReBuild: '目标版本实例减少，回滚只确保最终状态为该比例，期间当前版本实例会删除重建',
    targetVersion:'目标版本',
    choicegreyVersion: '选择灰度版本',
    plusOneObject: '+1 个过渡实例',
    updateInterval: '更新间隔',
    upgradeObjectInfo: '容器实例升级时间间隔，例如若为 0 秒，则 Pod 在 Ready 后就会被认为是可用状态，继续升级',
    suggest260s: '建议 2~60s',
    changeConfig: '服务 {serviceName} 配置更改中...',
    changeConfigSuccess: '服务 {serviceName} 配置已成功更改',
    changeConfigFailure: '更改服务 {serviceName} 配置失败',
    changeServiceConfig: '更改服务配置',
    choiceConfig: '选择配置',
    x86caculate: 'X86 计算',
    highPerformancecalculate:'高性能计算 GPU',
    rebootAllServiceInfo: ' Tips：重新选择配置 , 保存后系统将重启该服务的所有实例',
    serviceNotSupportReboot: '此服务已挂载存储卷，不支持滚动更新，服务会有短暂不可用时间！',
    rollupUpgrade: '将进行滚动升级。',
    serviceflex: '服务{ serviceName }伸缩中...',
    serviceflexObject: '服务 {serviceName} 已成功伸缩到 {realNum} 个实例',
    serviceflexFailure: '服务 {serviceName} 伸缩失败',
    manualScale: '手动水平扩展',
    changeObjectNumInfo: '实例数量调整，保存后系统将调整实例数量至设置预期。（若自动伸缩开启，则无法手动扩展）',
    independenceNoScale: '挂载独享型存储的服务不支持水平扩展',
    obejctNum: '实例数量',
    appName: '应用名称',
    autoDeploy: '自动部署',
    NotSet: '未设置',
    deleteServiceInfo: '注意：删除已设置自动部署的应用或服务，将自动删除其对应的自动部署规则',
    deleteAppInfo: '删除应用后，将自动删除对应对应自动部署规则',
    AppSetAutoDeploy: '应用{key}中, 服务{appRule}已设置自动部署',
    runingNotstart: '已经是运行中状态, 不需再启动',
    runingNotstartTip: '运行中状态的应用不需再次启动',
    runningStatus: '为运行中状态',
    stoppedText: '已经是已停止状态, 不需再停止',
    stoppedtip: '已停止状态的应用不需再次停止',
    stoppedtbInf: '为已停止状态',
    stoped: '已停止',
    runing: '运行中',
    RestartalertText: '是已停止状态, 不能做重新部署',
    Restarttip: '运行状态时应用才可以重新部署',
    RestarttbInf: '为已停止状态',
    RestartstateText: '可以重新部署',
    QuickRestaralertText: '是已停止状态, 不能快速重启',
    QuickRestartip: '运行状态时服务才可以快速重启',
    QuickRestartbInf: '为已停止状态',
    QuickRestaropt: '快速重启',
    QuickRestarstateText: '可以快速重启',
    sureDelete: '可以删除',
    app: '应用',
    service: '服务',
    youChoiceinfo: '你选择的{ checkedList } 个 { appOrService } 中有 { disableArr } 个 { alertText }',
    deleteAppinfo: '删除应用，该应用下所有服务的自动弹性伸缩策略也会被删除，',
    deleteAppstrategyinfo: '删除服务，该服务下的自动弹性伸缩策略也会被删除，',
    youconfirmApp: ' 您是否确定{ opt }这{ length }个{ stateText }的{ appOrService } ?',
    inputName: '请输入名称',
    input340character: '请输入3~40位字符',
    verificationNameInfo: '请输入中文、英文字母或数字开头，中间可下划线、连接符',
    strategyNameRepect: '策略名称重复',
    includeIllegalcharacter: '名称包含非法字符',
    pleaseChoiceType: '请选择类型',
    pleaseChoiceNode: '请选择节点',
    pleaseChoiceApp: '请选择应用',
    pleaseChoiceService: '请选择服务',
    node: '节点',
    service: '服务',
    pleaseHCoiceMonitorInterval: '请选择监控周期',
    pleaseInputName: '请输入名称',
    monitorInterval: '监控周期',
    monitorObject: '监控对象',
    monitorService: '监控服务',
    leastOneRule: '至少得有一项规则',
    pleaseChoiceOperation: '请选择运算符',
    monitorRepeat: '告警设置填写重复',
    pleaseInputNumber: '请填写数量',
    theNumberGreaterOne: '此数值需大于1',
    CPUuseRatio: 'CPU利用率',
    MemoryUsage: '内存使用',
    upLoadFlow: '上传流量',
    downLoadFlow: '下载流量',
    diskUsage: '磁盘利用率',
    containerObjectUseRadio: '= 所有容器实例占用CPU总和/CPU资源总量',
    containerObjectUseRadioNum: '= 所有容器实例占用内存总和/容器实例数量',
    alarmStrategyUpdating: '告警策略更新中',
    alarmStrategyUpdateSuccess: '告警策略更新成功',
    alarmStrategyUpdateFailure: '告警策略更新失败',
    alarmStrategyCreating: '告警策略创建中',
    alarmStrategyCreateSuccess: '告警策略创建成功',
    alarmStrategyCreateFailure: '告警策略创建失败',
    pleaseChoicemonitorGroup: '请选择告警通知组',
    argumentConfig: '参数设置',
    monitorRules: '告警规则',
    monitorBehavior: '告警行为',
    sendMessage: '发送通知',
    monitorMessagesChoiceInfo: '选择“是”，我们会向您发送监控信息和告警信息，选择“否”，我们将不会向你发送告警信息',
    monitorGroup: '告警通知组',
    newGroup: '新建组',
    validateEmail: '验证邮箱',
    inputCorrectEmailAddress: '请输入正确的邮箱地址',
    sendEmailSuccess: '向 {email} 发送邮件邀请成功',
    sendEmailFailure: '向 {email} 发送邮件邀请失败',
    validating: '验证中...',
    receiveInvitation: '已接收邀请',
    pleaseInput321character: '请输入3~21个字符',
    leastOneEmail: '请至少添加一个邮箱',
    createNotificationGroupFailure: '创建通知组失败',
    GroupNameExistInfo: '通知组名字已存在，请修改后重试',
    changeGroupFailure: '修改通知组失败',
    reValidateEmail: '{ time }秒后重新验证',
    remark: '备注',
    validatePhone: '验证手机',
    description: '描述',
    email: '邮箱',
    addEmail: '添加邮箱',
    scanQRbindWChat: '扫描二维码绑定微信',
    myPersonalItem: '我的个人项目',
    projectTextItem: '「 { projectText } 」项目',
    inCluserName: '在 { clusterName }',
    inQuotauseCondition: '中「{ resourceName }」配额使用情况',
    noLimit: '无限制',
    eidtQuota: '编辑配额',
    applyIncreaseQuota: '申请增加配额',
    createTime: '创建时间',
    noContainerObjec: '无容器实例',
    privateCache: '独享型 ( rbd )',
    privateCacheNFS: '共享型（GlusterFS）',
    shareCacheNFS: '共享型(NFS)',
    localStorage: '本地存储',
    unknown: '未知',
    noCacheVolume: '暂无缓存卷',
    readOnly: '只读',
    changeServiceVolumeFailureInfo: '修改服务存储卷失败，请重试',
    changeServiceVolumeSuccess: '修改服务存储卷成功',
    mirrorName: '镜像名称',
    modelMessage: '模型信息',
    bindModelAssembly: '绑定模型集',
    modelGroupMapToUserCatalogue: '模型集将映射到 用户目录/model/[模型集名称] 目录',
    resourceConfig: '资源配置',
    memory: '内存',
    systemDisk: '系统盘',
    CacheVolume: '存储卷',
    changeNoEffect: '修改尚未更新，请点击"应用修改"使之生效',
    appChange: '应用修改',
    cacheType: '存储类型',
    cache: '存储',
    containerDir: '容器目录',
    addContainerDir: '添加一个容器目录',
    editContainerDir: '编辑容器目录',
    addOnlyContainerDir: '添加容器目录',
    deleteContainerDir: '删除容器目录',
    makeSureRemoveContainerDir: '确定移除容器目录吗?',
    envChangeSuccess: '环境变量修改成功！',
    envChangeFailure: '环境变量修改失败！',
    variableNameValueNotEmpty: '变量名和变量值均不能为空',
    variableNameExist: '变量名已经存在，请修改！',
    saveNewEnv: '请先保存新增的环境变量',
    envVariable: '环境变量',
    VariableNameCanNotEmpty: '变量名不能为空！',
    NoEnvVariable: '暂无环境变量',
    commonVariable: '普通变量',
    encryptionVariable: '加密变量',
    pleaseInputValue: '请填写值',
    pleaseChoiceEncryptionObject: '请选择加密对象',
    variableName: '变量名',
    variableValue: '变量值',
    addEnvVariable: '添加环境变量',
    deleteEnvVariableOperation: '删除环境变量操作',
    deleteEnvVariableInfo: '你是否确定删除 [ {DeletingEnvName} ] 环境变量',
    systemDefaultDispatch: '系统默认调度',
    serviceNodeTag: '服务与节点标签',
    serviceAndServiceTag: '服务与服务标签',
    HostNameAndIp: '主机名及 IP',
    HostTag: '主机标签',
    NodeDispatch: '节点调度',
    bindPatter: '绑定方式',
    bindObject: '绑定对象',
    mirrorDefault: '镜像默认',
    priorityUseLocalMirror: '优先使用本地镜像',
    alwaysUseCloudMirror: '始终拉取云端该版本镜像',
    assistConfig: '辅助设置',
    intoPoint: '进入点',
    starCommand: '启动命令',
    timeZoneSet: '时区设置',
    useHostNodeTimeZone: '使用所在主机节点的时区',
    choicePromiseContainerAndHostNode: '选中后，可以保证容器始终与其所在的主机节点保持一致',
    dockerMountPoint: '容器挂载点',
    configClassify: '配置分类',
    configFile: '配置文件',
    noConfig: '暂无配置',
    clickCheckConfigFile: '点击查看配置文件',
    noClassified: '未分类',
    mountedAllConfigGroup: '已挂载整个配置组',
    commonConfig: '普通配置',
    encryptionConfig: '加密配置',
    getSecurityGroupErrorInfo: '获取安全组列表数据出错',
    getDetailErrorInfo: '获取详情出错',
    changeSecurityGroupFailure: '修改安全组失败',
    removeRelactionSecurityGroupFailure: '移除关联安全组失败',
    SecurityGroupName: '安全组名称',
    removeRelation: '移除关联',
    rleationRecurityGroup: '关联安全组',
    SecurityGroup: '安全组',
    removeRelationRecurityGroupInfo: '移除关联安全组导致隔离不再生效，请谨慎操作',
    confirmRmoveSecurityGroup: '确认移除关联安全组 { name }?',
    SecurityGroupComposeInfo: ' 安全组是由同一个集群内，具有相同安全保护需求并相互信任的服务组成',
    SecurityGroupIngressRules: ' 安全组内服务互通，安全组外服务需配置（ingress/egress）白名单规则',
    noRelationSecurityGroup: '关联安全组',
    tipsaddDomainInfo: '提示：添加域名后，CNAME地址会出现在这里',
    atMost10DomainName: '最多绑定10个域名',
    pleaseInputCorrectDomain: '请填写正确的域名',
    alreadyBindTheDomain: '已经绑定过该域名',
    saveDomaining: '保存域名信息中...',
    addDomainbindSuccess: '添加域名绑定成功',
    addDomainbindFailure: '添加域名绑定失败',
    noProvideCNAMEinfo: '该集群未定义域名，不能提供CNAME地址',
    priorityCloseHTTP: '请先关闭HTTPS后再删除绑定的域名',
    deleteBindDomain: '删除绑定域名中...',
    deleteBindDomainSuccess: '删除绑定域名成功',
    deleteBindDomainFailure: '删除绑定域名失败',
    afterBindDomainInfo: 'Tips：添加域名绑定后，需要在域名服务器上，将指定域名的CNAME指向下面表格中系统生成的"CNAME地址"',
    servicePort: '服务端口',
    domain: '域名',
    CNAMEaddress: 'CNAME地址',
    portRange: '端口范围 { minimumPort } ~ { maximumPort } ',
    conatinerPort: '容器端口',
    portDetailInfo: 'Tips：若该服务在访问方式中使用的网络出口没有在『基础设施』-『网络配置』中配置网络出口域名,则该服务的 http 协议无法正常使用',
    protocol: '协议',
    commonTitleInfo: '若该服务在访问方式中使用的网络出口没有在『基础设施』-『网络配置』中配置网络出口域名,则该服务的 http 协议无法正常使用',
    pleaseInputNumber: '请填入数字',
    ThisPortAlreadyUsed: '该端口已被使用',
    pleaseInput165535: '请填入1~65535',
    ThisPortAlreadyOccupy: '该端口已被占用',
    closeHTTPEditThisPort: '请先关闭HTTPS后再编辑此端口',
    saveEditPortThenEdit: '请保存正在编辑的端口后再编辑的端口',
    closeHTTPSThenDeletePort: '请先关闭HTTPS后再删除此端口',
    leastOnePort: '端口至少需要保留一个',
    saveEditPortThenAdd: '请保存正在编辑的端口后再添加新的端口',
    closeHTTPSEditProtocol: '请先关闭HTTPS后再修改此端口协议',
    portUpdating: '端口更新中',
    portUpdateSuccess: '端口更新成功',
    noPort: '无端口',
    pleaseInputPort: '请输入端口',
    pleaseInputContainerPort: '输入容器端口',
    pleaseChoiceProtocolType: '请选择协议类型',
    dynamicGeneration: '动态生成',
    designatedPort:'指定端口',
    addPortMap: '添加端口映射',
    makeSureDeletePort: '您是否确定要删除{ targetPort }端口吗?'
    }
}

export default defineIntlMessages(mapData)