#dockerFile{
  .ant-alert {
    margin-bottom: 0 !important;
    padding: 14px 24px !important;
    line-height: 20px;
    color: #1a7db6;
    font-size: 14px !important;
    background-color: #d9edf6;
    border: 1px dashed #85d7fd !important;
  }
  .tenxflowBox{
    .ant-card-body{padding:0}
  }
  .operaBox {
    padding-top: 20px;
    padding-bottom: 20px;
    position: relative;
    .searchBox {
      width: 170px;
      height: 32px;
    }
    .fa-search {
      position: absolute;
      top: 26px;
      left: 147px;
      font-size: 18px;
      color: #999;
    }
  }
  .tenxflowBox{
    .titleBox,.CodeTable{
      width: 100%;
      height: 50px;
      line-height: 50px;
      border-bottom: 1px solid #F2F2F2;
      font-size: 1.2em;
      .name{width: 25%;float: left;padding-left: 30px;}
      .editTime{width: 30%;float: left;padding-left: 30px;}
      .action{width: 20%;float: left;padding-left: 30px;}
      .type{width: 25%;float: left;padding-left: 30px;}
      .type.public{
        color: #5FB962;
        button{background: #5FB962;color: white;}
      }
      .type.private{
        color: #00A0EA;
        button{background: #5FB962;color: white}
      }
    }
    .CodeTable:hover{
      background: #FAFAFA;
    }
  }
}

//  show dockerFile modal

.dockerFileModal{
  .ant-modal-header{
    border:0;
    .ant-modal-title{color: #16B9FE;}
  }
  .ant-modal-body{
    background: #1A1A1A;
    color: #eee;
    border-radius: 0 0 5px 5px;
    overflow: hidden;
    .hrs{
      background: url('/img/cicd/bj_hr.png') repeat-x;
      width: 140%;
      height: 10px;
      margin-left: -20%;
    }
  }
}