/**
 * Licensed Materials - Property of tenxcloud.com
 * (C) Copyright 2018 TenxCloud. All Rights Reserved.
 */

/**
 *
 * intl for Sider
 * v0.1 - 2018-08-24
 *
 * @author zhangpc
 *
 */

import { defineIntlMessages } from '../../../common/tools'

export const mapData = {
  prefix: 'Sider',
  data: {
    tenantOverview: '概览',
    tenantUser: '成员管理',
    tenantTeam: '团队管理',
    tenantProject: '项目管理',
    tenantProjectPermossions: '项目权限',
    tenantClusterAuth: '集群授权审批',
    tenantResourcequotaAuth: '配额审批',
    tenantResourcequotaApply: '配额申请',
    tenantLdap: '集成企业目录',
    onlyAdmin: '仅系统管理员可见',
    onlyInfraAndAdmin: '仅基础设施管理员、系统管理员可见',
    onlyPlatformAndAdmin: '仅平台管理员、系统管理员可见',
    onlyNormalUser: '仅普通用户可见',
    version: '平台版本',
    license: '授权管理',
    openApi: '开放 API',
    advancedSetting: '高级设置',
    personalized: '个性外观',
    cleaningTool: '清理工具',
    overview: '总览',
    appManage: '应用管理',
    appStack: '工作负载',
    netManagement: '网络管理',
    storageManagement: '存储管理',
    appCenter: '交付中心',
    databaseCache: '数据库与缓存',
    aiDeepLearning: 'AI 深度学习',
    Notebook: 'Notebook',
    integration: '集成中心',
    manangeMonitor: '管理与监控',
    account: '帐户中心',
    tenant: '租户管理',
    setting: '系统设置',
    cluster: '基础设施',
    appManage: '应用管理',
    apps: '应用',
    services: '服务',
    containers: '容器',
    storage: '存储',
    snapshot: '独享存储快照',
    configs: '服务配置',
    discover: '服务发现',
    dnsRecord: 'DNS 记录',
    customStorage: '自定义存储',
    securityGroup: '安全组 (防火墙)',
    loadBalance: '应用负载均衡',
    autoScale: '自动伸缩策略',
    vmWrap: '传统应用',
    vmList: '传统应用环境',
    appCenter: '交付中心',
    appTemplate: '应用模板',
    imageProjects: '镜像仓库',
    wrapManage: '应用包管理',
    stackCenter: '编排文件',
    wrapStore: '应用商店',
    wrapCheck: '发布审核',
    cicdOverview: '概览',
    cicdCodeRepos: '代码仓库',
    buildImage: '构建镜像',
    pipelines: '流水线',
    Dockerfile: 'Dockerfile',
    cachedVolumes: '缓存卷',
    thirdparty: '第三方工具',
    mysqlCluster: 'MySQL 集群',
    redisCluster: 'Redis 集群',
    zookeeperCluster: 'ZooKeeper 集群',
    elasticsearchCluster: 'ES 集群',
    largeScaleTrain: '大规模训练',
    dataSet: '数据集',
    modelSet: '模型集',
    aiModelService: 'AI 模型应用',
    manangeMonitor: '管理与监控',
    audit: '操作审计',
    queryLog: '日志查询',
    monitorPanel: '监控面板',
    alarmSetting: '告警设置',
    alarmRecord: '告警记录',
    noticeGroup: '通知组',
    myAccount: '我的帐户',
    consumptions: '消费记录',
    payments: '充值记录',
    clusterManage: '集群管理',
    globalConfig: '全局配置',
    iaas: '资源池',
    clusterAutoscale: '集群伸缩策略',
    iaas: '资源池',
    clusterMonitor: '系统服务监控',
    clusterBackup: '平台数据备份',
    outdentMenu: '展开导航栏',
    indentMenu: '收起',
    deployManage: '部署管理',
    middlewareCenter: '服务目录',
    StatefulSet: 'StatefulSet',
    Job: 'Job',
    CronJob: 'CronJob',
    Deployment: 'Deployment',
    Pod: 'Pod',
    privateStorage: '独享型存储',
    shareStorage: '共享型存储',
    localStorage: '本地存储',
    appStackPro: '堆栈',
    appStackTemplates: '堆栈模板',
    appStackDesigner: '堆栈设计器',
  },
}

export default defineIntlMessages(mapData)
